### ISSUE TITLE
Make milestone1 requirements more clear

### ISSUE THREAD

**Issue by jchen9314** [UBC-MDS/DSCI_522_jchen9314_apchiodo#15]
@apchiodo 
## First script
- reads in some data and saves a clean/tidy version of it. 
- **take two arguments**:
	1. input file path (data/file.csv)
	2. output file path (pd.to\_csv(path))(e.g., data/cleaned_data.csv)
- notes: choose more descriptive filenames

## Second script
- reads the data from the first script and creates an exploratory visualization (EDA).
- **take two arguments**:
	1. a path/filename pointing to the data
	2. a path/filename prefix where to write the figure to and what to call it (e.g., results/this_eda.png)

## Third script
- reads the data from the first script, performs some statistical or machine learning analysis (e.g., creates a summary table) and writes these numerical data to file in CSV or TSV format. 
- **take two arguments**:
	1. a path/filename pointing to the data
	2. a path/filename where to write the file to and what to call it (e.g., results/summarized_data.csv)

## Fourth script
- reads the output of the first and/or third script, generate some summary/final result table(s) and/or figure(s) and save them to files.
- take two arguments:
	1. a path/filename pointing to the data
	2. a path/filename prefix where to write the figure(s)/table(s) to and what to call it (e.g., results/this_analysis)

## Report
- an .Rmd or .ipynb actually, that presents original data, the statistical summaries, and/or the figures in a little report. 
- There should be a written narrative in this document that:
	- 1. introduces and justifies your question 
	- 2. introduces the data set
	- 3. presents the findings/results
	- 4. interprets the findings/results in context of the question. 
	- 5. Some critique of the analysis is also expected (limitations, assumptions, etc) 
	- 6. a statement of future directions (what would you do next if you had more time to work on this). 
- 1-2 written pages (excluding figures, tables and references).
- have a reference section and cite 2-3 external sources (data source can be one of these citations).

**Comment by apchiodo** [comment]
Seems like we're in good shape here.  Closing issue.
