### ISSUE TITLE
What are the predictors? 

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_jchen9314_apchiodo#20]
You want to predict the quality score but your dataset contains 11 quality scores (scores between 0 and 10).   It may not be reasonable to have 10 predicting classes in this classification prediction problem. Do you plan to group the quality scores? (e.g., two groups of poor and good quality, or 3 groups or 4 groups, etc.)

**Comment by apchiodo** [comment]
In the data set, there is actually only 6 unique values for quality (3, 4, 5, 6, 7, 8).  After some preliminary data exploration, we realized that we could split the data into two categories (<=5 and > 5) with a fairly even amount of data in each group.   The new groups could be labelled as "Poor" and "Good".

**Comment by apchiodo** [comment]
closing issue.

**Comment by aimirza** [comment]
Good idea
