### ISSUE TITLE
incorrect usage in script 2(eda)

### ISSUE THREAD

**Issue by jchen9314** [UBC-MDS/DSCI_522_jchen9314_apchiodo#28]
@apchiodo Hey Tony, I think the usage in script 2 is invalid. The output should be EDA figures instead of .csv file.

**Comment by apchiodo** [comment]
Fixed! Nice find.

https://github.com/UBC-MDS/DSCI_522_jchen9314_apchiodo/pull/30/commits/a294894f3de510f4f9f95201467f371a765030ee

**Comment by jchen9314** [comment]
Looks nice!
