### ISSUE TITLE
Milestone1 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_jchen9314_apchiodo#43]
**You may close this issue when all issues are resolved and checked.** 

**Mechanics**
- [x] Change eda.R script name to something more descriptive.
- [x] In your main README.md and script self-documentation, you have arguments such as "results/figures" and "results/." You need an argument with the structure "path/filename," where to write the file to and what to call it (e.g., data/cleaned_data.csv).

**Reasoning**
- [x]  Please mention what type each variable is (e.g., categorical, ordinal, numeric, etc.)
- [x] Explain in your main README.md what each command does, what their inputs its accepts and what the outputs are. 
- [x] Add (Figure 1) after "...the data became more evenly balanced between classes." You need to refer to each figure in your text. 
- [x] In the discussion, explain what alcohol, volatile acidity, and sulphates has to do with wine and why these variables may be important for wine quality. 
- [x] So the more alcohol the better quality? So if alcohol percentage is 90% that will likely have a high quality rating? The decision tree graph might help you answer this question. 
- [x] Do not speak informally in formal reports. 
- [x] Graph your decision tree model to display how your model works. Don't plot the whole tree. 

**Visualization**
- [x] More descriptive Figure and table captions. Captions should stand alone. Meaning, the reader should understand the figure by examining the graph and caption alone, and not refer back to the text. For example: "Figure 1. Mean pregnancy length for first babies pregnancy and for other (non-first baby) pregnancy length. Error bars represent 95% confidence intervals generated by boostrapping.)"
- [x] To make figure 1. B more understandable, label the "low" and "high" in place of 0 and 1. 

**Quality -- Readability and Documentation**
- [x]  line 2 in eda.R script says "data_clean.R." Is this correct?
- [x] clean_data.R self-documentation doesn't clearly explain what it does. What are the two targets? 
- [x] Regarding the script eda.R, rename plot1, plot2, plot1_2, and plot3 to more meaningful names such that the reader has an idea about the differences between these plots. 
- [x] Make your codes reproducible. See [this](http://scikit-learn.org/stable/faq.html#how-do-i-set-a-random-state-for-an-entire-execution). 

**Quality -- Robustness and Maintainability**
- [x] Should have a unit test in each script (because we did not clearly mention this in the instructions, we did not reduct points for not having a unit test)

**Grammar and Spelling**
- [x] Capitalize the first letter in each cell in all your tables. 
- [x] (main README.md) 5 grammar or spelling mistakes
- [x] (report) 3 grammar or spelling mistakes. Need to use more definite/indefinite articles

**Comment by jchen9314** [comment]
@aimirza Hey Ali, we are somewhat confused about "Need to use more definite/indefinite articles". Could you explain a little bit more on it?

**Comment by aimirza** [comment]
You are missing either the definite article "the" or an indefinite article "a" before some nouns.
