### ISSUE TITLE
Milestone2 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522_jchen9314_apchiodo#59]
- [x] A bit jargoney for the README/overview IMHO and difficult to know what this sentence means (if I wasn't familiar with the data), and also a bit incorrect (you only have one target - wine quality, but it has multiple categories or values). Try clarifying and simplifying. Otherwise the overview is great!

- [x] Text in decision tree graphic is far too small to be useful. Could simplify if by rotating it 90 degrees (more room for bigger text!) and including less info on the graphic (value, samples and gini could be in a table in an appendix).

- [x] Should write unit tests for functions they write (other than the main function).

*All credit goes to Prof. Tiffany Timbers. These are her comments.

**Comment by apchiodo** [comment]
Addressed all comments.
